name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          theme=$(curl -s https://api.github.com/repos/mustafaemresahin/mustafaemresahin/contents/README.md | jq -r '.content')
          if [[ "$theme" == *'data-theme="light"'* ]]; then
            updated_theme=${theme/'data-theme="light"'/data-theme="dark"}
          else
            updated_theme=${theme/'data-theme="dark"'/data-theme="light"}
          fi
          updated_content=$(echo -n "$updated_theme" | base64)
          curl -X PUT \
               -H "Authorization: token ${{ secrets.ACTIONS_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"message": "Update theme based on GitHub Actions", "content": "'"$updated_content"'"}' \
               "https://api.github.com/repos/mustafaemresahin/mustafaemresahin/contents/README.md"
